### PR TITLE
WineShop class added

### PR DESCRIPTION
**Pull request by 01gaM**
+ object info to logs method
+ object info to file method

### CODE REVIEW

**Review by chinarev — COMMENTED** [review]
Кулл! Можно переименовать класс в "Shops", как на диаграмме классов.

**Review by DeLonghi — APPROVED** [review]
Expected Wine class, but ok

**Comment by 01gaM** [comment]
@DeLonghi WineShop class was expected
https://trello.com/c/sPfPFLSa/6-wineshop-class

**Comment by DeLonghi** [comment]
My mistake.

**Pull request merged**
